export interface Photo {
  id: string;
  src: string;
  thumb: string;
  alt: string;
  aspect: "landscape" | "portrait" | "square";
  category: "editorial" | "nature";
}

export const categories = [
  { id: "editorial" as const, label: "Editorial" },
  { id: "nature" as const, label: "Nature" },
];

// Auto-generated by scripts/process-photos.sh
// To add photos: ./scripts/process-photos.sh <directory-or-file>
// NOTE: category defaults to "editorial". Edit photos.ts to recategorize.
export const photos: Photo[] = [
  { id: "_dsc1789", src: "/photos/_dsc1789.jpg", thumb: "/photos/thumbs/_dsc1789.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "_dsc2901", src: "/photos/_dsc2901.jpg", thumb: "/photos/thumbs/_dsc2901.webp", alt: "", aspect: "landscape", category: "editorial" },
  { id: "_dsc4106", src: "/photos/_dsc4106.jpg", thumb: "/photos/thumbs/_dsc4106.webp", alt: "", aspect: "landscape", category: "nature" },
  { id: "_dsc8375", src: "/photos/_dsc8375.jpg", thumb: "/photos/thumbs/_dsc8375.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "dsc_0479", src: "/photos/dsc_0479.jpg", thumb: "/photos/thumbs/dsc_0479.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "dsc_1523", src: "/photos/dsc_1523.jpg", thumb: "/photos/thumbs/dsc_1523.webp", alt: "", aspect: "portrait", category: "nature" },
  { id: "dsc_1656", src: "/photos/dsc_1656.jpg", thumb: "/photos/thumbs/dsc_1656.webp", alt: "", aspect: "portrait", category: "nature" },
  { id: "dsc_2123", src: "/photos/dsc_2123.jpg", thumb: "/photos/thumbs/dsc_2123.webp", alt: "", aspect: "portrait", category: "nature" },
  { id: "dsc_2604", src: "/photos/dsc_2604.jpg", thumb: "/photos/thumbs/dsc_2604.webp", alt: "", aspect: "portrait", category: "nature" },
  { id: "dsc_3178", src: "/photos/dsc_3178.jpg", thumb: "/photos/thumbs/dsc_3178.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "dsc_3370", src: "/photos/dsc_3370.jpg", thumb: "/photos/thumbs/dsc_3370.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "dsc_3935", src: "/photos/dsc_3935.jpg", thumb: "/photos/thumbs/dsc_3935.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "dsc_5736", src: "/photos/dsc_5736.jpg", thumb: "/photos/thumbs/dsc_5736.webp", alt: "", aspect: "portrait", category: "nature" },
  { id: "dsc_6174", src: "/photos/dsc_6174.jpg", thumb: "/photos/thumbs/dsc_6174.webp", alt: "", aspect: "portrait", category: "editorial" },
  { id: "dsc_6278", src: "/photos/dsc_6278.jpg", thumb: "/photos/thumbs/dsc_6278.webp", alt: "", aspect: "landscape", category: "nature" },
];

export function getPhoto(id: string): Photo | undefined {
  return photos.find((p) => p.id === id);
}

export function getAdjacentPhotos(id: string, category?: string): { prev: Photo | undefined; next: Photo | undefined } {
  const filtered = category ? photos.filter((p) => p.category === category) : photos;
  const idx = filtered.findIndex((p) => p.id === id);
  return {
    prev: idx > 0 ? filtered[idx - 1] : undefined,
    next: idx < filtered.length - 1 ? filtered[idx + 1] : undefined,
  };
}
