#!/bin/bash
#
# Process photos for the website gallery.
#
# Usage:
#   ./scripts/process-photos.sh ~/Desktop/jarmokuvia
#   ./scripts/process-photos.sh ~/Desktop/jarmokuvia/new-photo.jpg
#
# Processes JPG/JPEG/PNG files:
#   - Resizes to max 2400px on the longest edge
#   - Converts to JPEG at 85% quality
#   - Outputs to public/photos/ with lowercase filenames
#   - Auto-detects aspect ratio (portrait/landscape/square)
#   - Regenerates app/photos.ts with all photos in public/photos/
#
# Requires: sips (macOS built-in)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUT_DIR="$PROJECT_DIR/public/photos"
PHOTOS_TS="$PROJECT_DIR/app/photos.ts"
MAX_SIZE=2400
QUALITY=85

mkdir -p "$OUT_DIR/thumbs"

# Collect input files
FILES=()
if [ -d "$1" ]; then
  for f in "$1"/*.{jpg,JPG,jpeg,JPEG,png,PNG}; do
    [ -f "$f" ] && FILES+=("$f")
  done
elif [ -f "$1" ]; then
  FILES+=("$1")
else
  echo "Usage: $0 <directory-or-file>"
  exit 1
fi

if [ ${#FILES[@]} -eq 0 ]; then
  echo "No image files found."
  exit 1
fi

echo "Processing ${#FILES[@]} images..."

for f in "${FILES[@]}"; do
  basename=$(basename "$f")
  # Lowercase, replace spaces with hyphens, strip extension
  name=$(echo "${basename%.*}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
  outfile="$OUT_DIR/${name}.jpg"

  # Get dimensions
  w=$(sips -g pixelWidth "$f" 2>/dev/null | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$f" 2>/dev/null | awk '/pixelHeight/{print $2}')

  # Resize based on longest edge
  if [ "$w" -gt "$h" ]; then
    if [ "$w" -gt "$MAX_SIZE" ]; then
      sips --resampleWidth "$MAX_SIZE" "$f" --out "$outfile" -s format jpeg -s formatOptions "$QUALITY" >/dev/null 2>&1
    else
      sips "$f" --out "$outfile" -s format jpeg -s formatOptions "$QUALITY" >/dev/null 2>&1
    fi
  else
    if [ "$h" -gt "$MAX_SIZE" ]; then
      sips --resampleHeight "$MAX_SIZE" "$f" --out "$outfile" -s format jpeg -s formatOptions "$QUALITY" >/dev/null 2>&1
    else
      sips "$f" --out "$outfile" -s format jpeg -s formatOptions "$QUALITY" >/dev/null 2>&1
    fi
  fi

  # Generate WebP thumbnail
  magick "$outfile" -resize "1200x1200>" -quality 85 "$OUT_DIR/thumbs/${name}.webp"

  echo "  $basename -> ${name}.jpg + thumb"
done

# Regenerate photos.ts from all files in public/photos/
echo ""
echo "Regenerating $PHOTOS_TS..."

cat > "$PHOTOS_TS" << 'HEADER'
export interface Photo {
  id: string;
  src: string;
  thumb: string;
  alt: string;
  aspect: "landscape" | "portrait" | "square";
  category: "editorial" | "nature";
}

export const categories = [
  { id: "editorial" as const, label: "Editorial" },
  { id: "nature" as const, label: "Nature" },
];

// Auto-generated by scripts/process-photos.sh
// To add photos: ./scripts/process-photos.sh <directory-or-file>
// NOTE: category defaults to "editorial". Edit photos.ts to recategorize.
export const photos: Photo[] = [
HEADER

for img in "$OUT_DIR"/*.jpg; do
  [ -f "$img" ] || continue
  name=$(basename "$img" .jpg)
  w=$(sips -g pixelWidth "$img" 2>/dev/null | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$img" 2>/dev/null | awk '/pixelHeight/{print $2}')

  ratio=$(echo "$w $h" | awk '{r=$1/$2; if (r>1.1) print "landscape"; else if (r<0.9) print "portrait"; else print "square"}')

  echo "  { id: \"$name\", src: \"/photos/${name}.jpg\", thumb: \"/photos/thumbs/${name}.webp\", alt: \"\", aspect: \"$ratio\", category: \"editorial\" }," >> "$PHOTOS_TS"
done

cat >> "$PHOTOS_TS" << 'FOOTER'
];

export function getPhoto(id: string): Photo | undefined {
  return photos.find((p) => p.id === id);
}

export function getAdjacentPhotos(id: string, category?: string): { prev: Photo | undefined; next: Photo | undefined } {
  const filtered = category ? photos.filter((p) => p.category === category) : photos;
  const idx = filtered.findIndex((p) => p.id === id);
  return {
    prev: idx > 0 ? filtered[idx - 1] : undefined,
    next: idx < filtered.length - 1 ? filtered[idx + 1] : undefined,
  };
}
FOOTER

count=$(ls "$OUT_DIR"/*.jpg 2>/dev/null | wc -l | tr -d ' ')
echo "Done. $count photos in gallery."
